### ISSUE TITLE
Add/update autocomplete attributes pls

### ISSUE THREAD

**Issue by Akumetsu-Dev** [atom/autocomplete-html#46]
Hello, i can't pull a requests so, i use this side to publish my request and sorry.

autocomplete-html isn't completing attributes of the html, when i try to use the tag input and put a type, the attribute values not appear, and this happens with the majorities of html tags.

Thankyou

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
