### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ng-submit' of undefined

### ISSUE THREAD

**Issue by wil93** [atom/autocomplete-html#52]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.4.15
**OS**: "Arch Linux"
**Thrown From**: [autocomplete-html](https://github.com/atom/autocomplete-html) package 0.7.2

### Stack Trace

Uncaught TypeError: Cannot read property 'ng-submit' of undefined

```
At /usr/lib/atom/node_modules/autocomplete-html/lib/provider.js:252

TypeError: Cannot read property 'ng-submit' of undefined
    at Object.getAttributeValues (/usr/lib/atom/node_modules/autocomplete-html/lib/provider.js:252:46)
    at Object.getAttributeValueCompletions (/usr/lib/atom/node_modules/autocomplete-html/lib/provider.js:192:21)
    at Object.getSuggestions (/usr/lib/atom/node_modules/autocomplete-html/lib/provider.js:24:21)
    at /usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-jinja2 0.6.0 
copy-as-rtf 0.9.3 
copy-with-syntax 0.0.3 
hard-wrap 1.1.0 
hidpi 0.12.0 
language-latex 1.0.0 
latex 0.42.3 
linter 1.11.23 
linter-flake8 2.1.4 
linter-gcc 0.7.1 
linter-javac 1.9.4 
multi-wrap-guide 0.28.2 
nuclide 0.209.0 
```

**Comment by 50Wliu** [comment]
> Electron: 1.4.15

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.

**Comment by wil93** [comment]
I'm using this one: https://www.archlinux.org/packages/community/x86_64/atom/

It's the official one right?

**Comment by 50Wliu** [comment]
No.  The version you're using is rather notorious for using mismatched components.  The official one is from https://atom.io.
