### ISSUE TITLE
Stylesheet option for rel="" attribute.

### ISSUE THREAD

**Issue by ghost** [atom/autocomplete-html#74]
In attributes list for rel="" is no stylesheet option for it.Stylesheet option is using for connect stylesheets which is primary and often used it might be added to autocomplete list for rel="" atribute.

**Comment by 50Wliu** [comment]
It's not showing up even though it should. https://github.com/atom/autocomplete-html/blob/7b5fd2a80457e79020147314d1622ba722b54d96/completions.json#L1749

**Comment by NickolasGame** [comment]
Can you try to reproduce this on your machine ? I want to know is it unically for my?

**Comment by 50Wliu** [comment]
@NickolasGame Sorry, I wasn't clear.  I did reproduce the bug.

**Comment by NickolasGame** [comment]
OK

**Comment by NickolasKyrylyuk** [comment]
Any progress on it ?

**Comment by abaracedo** [comment]
Just for try it I have rewritten the condition to return the options using nested `if` and it returns `stylesheet` in the options.

<img width="397" alt="stylesheet is shown" src="https://user-images.githubusercontent.com/9487675/31031448-df98a938-a558-11e7-8e5e-cbd38e219929.png">

This is the rewritten method

```coffee
  getAttributeValues: (tag, attribute) -> (
    # Some local attributes are valid for multiple tags but have different attribute values
    # To differentiate them, they are identified in the completions file as tag/attribute

    if this.completions.attributes != null
      attributes = this.completions.attributes
      if attributes[tag + "/" + attribute] != null
        options = attributes[tag + "/" + attribute]
        if options.attribOption != null
          return options.attribOption
        else
          return []
  )
```

I am not going to PR this solution because is not a good one but I think that can give some clues about what is happening.

**Comment by abaracedo** [comment]
After submit the PR I noticed that the code I put before is not correct because the condition used in the code is not a nested `if`, it is a `ternary` condition:

`this.completions.attributes != null ? this.completions.attributes.attribOption ? attributes[tag + "/" + attribute] != null ? attributes[tag + "/" + attribute].attribOption : [] `
