### ISSUE TITLE
By default, the HTML extension file cannot complete the code properly

### ISSUE THREAD

**Issue by linjialiang** [atom/autocomplete-html#87]
> By default, the HTML extension file cannot complete the code properly

![html](https://user-images.githubusercontent.com/8848263/44385503-2f0bbd80-a552-11e8-9a85-cfdb8b4d6b85.gif)

**Comment by linjialiang** [comment]
> The last thing I want to say is that the growing list of problems with the atom editor is unacceptable to anyone who loves it!

**Comment by linjialiang** [comment]
@50Wliu @kevinsawicki @benogle

**Comment by linjialiang** [comment]
> I went back to normal after I reinstalled it

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:
