### ISSUE TITLE
Autocomplete leaves a bracket at the start

### ISSUE THREAD

**Issue by piotrz37** [atom/autocomplete-html#97]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When typing HTML and using auto-completed it leaves an extra bracket "<" at the start of the tag. This happens when starting a new document and when using tags such as "<div>".

### Steps to Reproduce

1. Open a new html file
2. Begin by typing "<htm" and press tab to auto-complete the template
3. The template will fill in but start with "<<!DOCTYPE html>"

Other reproduction steps
1. Open any html file
2. Begin typing "<div" and hit tab to auto-complete
3. The div will complete with the closing tag and class but start with "<<div" rather than "<div" like it should.

**Expected behavior:** All tags start with single bracket "<" after auto-complete

**Actual behavior:** All auto-completed tags start with 2 brackets "<<" 

**Reproduces how often:** Every time.

### Versions

Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
Running on Apple OS 10.14.5

### Additional Information

Nothing more to add.

**Comment by rsese** [comment]
Thanks for the report - a GIF/screencast would confirm but I'm guessing that you're selecting the snippet suggestion rather than the autocomplete suggestion?  Do you see 2 `html` options like this?

![html-completion](https://user-images.githubusercontent.com/734194/58836504-98ab1300-861e-11e9-838b-25676fd044b8.png)

The first one is the `html` snippet (the green icon for it is missing in 1.37.0) which will just insert the snippet and that already includes the opening bracket while the autocomplete-html suggestion (has the red icon) will suggest as you type e.g.:

![html-autocomplete](https://user-images.githubusercontent.com/734194/58836688-12430100-861f-11e9-9979-dde63bbce414.gif)

So if you want the snippet, you should just type `html` without the opening bracket.  And the same for `div`.

If I'm misunderstanding, please let me know and share a GIF/screencast so we can take a look.
